# Generated by Django 5.2.4 on 2025-12-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winlos_app', '0003_exam_examquestion_examoption_authcode_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('cinematography', 'Cinematography'), ('scriptwriting', 'Scriptwriting'), ('video_editing', 'Video Editing'), ('sound_engineering', 'Sound Engineering'), ('filmmaking', 'Filmmaking'), ('set_Design', 'Set_Design')], max_length=50),
        ),
    ]
