# Generated by Django 5.2.4 on 2025-12-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winlos_app', '0004_alter_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
