# Generated by Django 5.2.4 on 2025-12-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winlos_app', '0005_lesson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('cinematography', 'Cinematography'), ('scriptwriting', 'Scriptwriting'), ('video_editing', 'Video Editing'), ('sound_engineering', 'Sound Engineering'), ('filmmaking', 'Filmmaking'), ('set_design', 'Set Design'), ('vfx_design', 'VFX Design'), ('directing', 'Directing'), ('acting', 'Acting'), ('indie_filmmaker_bundle', 'Indie Filmmaker Bundle'), ('the_storyteller_bundle', 'The Storyteller Bundle'), ('the_technical_bundle', 'The Technical Bundle'), ('the_content_creation_bundle', 'The Content Creation Bundle'), ('the_business_of_film_making_bundle', 'The Business of Film Making Bundle')], max_length=50),
        ),
    ]
