# Generated by Django 5.2.4 on 2025-12-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winlos_app', '0006_alter_course_course_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
