# Generated by Django 5.2.4 on 2025-12-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winlos_app', '0007_alter_lesson_options_lesson_duration_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='duration_seconds',
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
