# Generated by Django 5.2.4 on 2025-12-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winlos_app', '0008_remove_lesson_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='selected_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
