# Generated by Django 5.2.4 on 2025-12-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winlos_app', '0009_examattempt_selected_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.FileField(blank=True, help_text='Upload certificate template PDF for this course', null=True, upload_to='certificates/templates/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Final generated certificate', null=True, upload_to='certificates/generated/'),
        ),
    ]
