# Generated by Django 5.2.4 on 2025-12-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winlos_app', '0010_course_certificate_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='exam',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Final generated certificate PDF', null=True, upload_to='certificates/generated/'),
        ),
    ]
