# Generated by Django 5.2.4 on 2025-12-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winlos_app', '0011_remove_certificate_exam_alter_certificate_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='certificate_template',
        ),
    ]
