# Generated by Django 5.2.4 on 2025-12-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winlos_app', '0012_remove_course_certificate_template'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='pdf_file',
        ),
    ]
