# Generated by Django 5.2.4 on 2025-12-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winlos_app', '0016_alter_account_area_of_expertise_alter_account_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
